server:
  port: 8080
  timeout: 30s
database:
  host: localhost
  port: 5432
  name: products
  user: postgres
  password: password
redis:
  host: localhost
  port: 6379
rabbitmq:
  url: amqp://guest:guest@localhost:5672/